"""Add image_url column to Tour

Revision ID: 4188ecde0355
Revises: 5d2b22b8f4e9
Create Date: 2025-07-19 14:32:44.229906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4188ecde0355'
down_revision = '5d2b22b8f4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
