"""Create payment table

Revision ID: 5b3f1d11f928
Revises: 5d5b32d4c776
Create Date: 2025-07-23 14:47:49.003553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3f1d11f928'
down_revision = '5d5b32d4c776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('review_tour_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tour', ['tour_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('review_tour_id_fkey'), 'tour_package', ['tour_id'], ['id'])

    # ### end Alembic commands ###
