"""Create payment table

Revision ID: 5d5b32d4c776
Revises: 0abbdae4048e
Create Date: 2025-07-23 14:47:22.735224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5b32d4c776'
down_revision = '0abbdae4048e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('review_tour_package_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tour_package', ['tour_id'], ['id'])
        batch_op.drop_column('tour_package_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_package_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('review_tour_package_id_fkey'), 'tour_package', ['tour_package_id'], ['id'])
        batch_op.drop_column('tour_id')

    # ### end Alembic commands ###
