"""Added image field to Destination model

Revision ID: 72c6657a408a
Revises: beea3c718992
Create Date: 2025-07-22 14:07:37.139675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c6657a408a'
down_revision = 'beea3c718992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
