"""Add fee field to Tour

Revision ID: 93e545a2ef8b
Revises: f9cec4f6c19e
Create Date: 2025-07-21 13:17:28.425872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e545a2ef8b'
down_revision = 'f9cec4f6c19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_column('fee')

    # ### end Alembic commands ###
