"""Add image column (nullable) to Tour

Revision ID: f9cec4f6c19e
Revises: 4188ecde0355
Create Date: 2025-07-19 23:40:27.183196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cec4f6c19e'
down_revision = '4188ecde0355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
